import {
  Complaint,
  ComplaintStatus,
  User,
  Role,
  Announcement,
  Achievement,
  Importance,
} from "../types";

// Mock Complaints Data
export const mockComplaints: Complaint[] = [
  {
    id: "1",
    trackingNumber: "TRK-001",
    district: "Al Olaya",
    category: "infrastructure",
    importance: Importance.HIGH,
    title: "Pothole on Main Street causing traffic issues",
    description:
      "Large pothole on Main Street causing traffic accidents and vehicle damage. Multiple reports from residents.",
    status: ComplaintStatus.PENDING,
    createdAt: "2024-01-15T10:00:00Z",
    phoneNumber: "0912345678",
    attachments: [],
    pinned: false,
    submitterName: "Ahmed Hassan",
    location: "Main Street & Oak Avenue",
    citizenHelp: "Fill the pothole with asphalt and resurface the area",
    solutionInfo: "",
    refusalReason: "",
    notes: "High priority - multiple reports received, affects traffic flow",
    estimatedReviewTime: "2 days",
    assignedMuktarId: "muk1",
    assignedAdminId: "admin1",
    assignedManagerId: "mgr1",
  },
  {
    id: "2",
    trackingNumber: "TRK-002",
    district: "Al Malaz",
    category: "sanitation",
    importance: Importance.MEDIUM,
    title: "Garbage collection delayed for 3 days",
    description:
      "Garbage collection delayed for 3 days, causing overflow and health concerns in residential area",
    status: ComplaintStatus.COMPLETED,
    createdAt: "2024-01-14T14:30:00Z",
    phoneNumber: "0998765432",
    attachments: [],
    pinned: false,
    submitterName: "Fatima Al-Zahra",
    location: "Residential Area Block C",
    citizenHelp: "Increase collection frequency and add more bins",
    solutionInfo: "Collection schedule adjusted to twice weekly",
    refusalReason: "",
    notes: "Resolved - schedule updated and additional bins deployed",
    estimatedReviewTime: "1 day",
    assignedMuktarId: "muk2",
    assignedAdminId: "admin2",
    assignedManagerId: "mgr1",
  },
  {
    id: "3",
    trackingNumber: "TRK-003",
    district: "Al Rawdah",
    category: "lighting",
    importance: Importance.LOW,
    title: "Street light not working on Elm Street",
    description:
      "Street light not working on Elm Street, creating safety hazard at night",
    status: ComplaintStatus.PENDING,
    createdAt: "2024-01-16T08:15:00Z",
    phoneNumber: "0955566677",
    attachments: [],
    pinned: false,
    submitterName: "Omar Ibn Khattab",
    location: "Elm Street between 5th and 6th",
    citizenHelp: "Replace the faulty bulb or entire fixture",
    solutionInfo: "",
    refusalReason: "",
    notes: "Maintenance team notified, scheduled for inspection",
    estimatedReviewTime: "3 days",
    assignedMuktarId: "muk3",
    assignedAdminId: "",
    assignedManagerId: "",
  },
  {
    id: "4",
    trackingNumber: "TRK-004",
    district: "Al Sulimaniyah",
    category: "water",
    importance: Importance.HIGH,
    title: "Water main leak causing flooding",
    description: "Water main leak causing flooding and water pressure issues",
    status: ComplaintStatus.IN_PROGRESS,
    createdAt: "2024-01-13T16:45:00Z",
    phoneNumber: "0924681357",
    attachments: [],
    pinned: false,
    submitterName: "Aisha Bint Abu Bakr",
    location: "Water Street & River Road",
    citizenHelp: "Repair the leak immediately to prevent further damage",
    solutionInfo: "",
    refusalReason: "",
    notes: "Emergency repair team dispatched, temporary fix applied",
    estimatedReviewTime: "1 day",
    assignedMuktarId: "muk4",
    assignedAdminId: "admin1",
    assignedManagerId: "mgr2",
  },
  {
    id: "5",
    trackingNumber: "TRK-005",
    district: "Al Murabba",
    category: "electricity",
    importance: Importance.HIGH,
    title: "Power outage affecting entire neighborhood",
    description: "Power outage affecting entire neighborhood for 4 hours",
    status: ComplaintStatus.COMPLETED,
    createdAt: "2024-01-12T22:30:00Z",
    phoneNumber: "0987654321",
    attachments: [],
    pinned: false,
    submitterName: "Ali Ibn Abi Talib",
    location: "Neighborhood wide - Block A, B, C",
    citizenHelp: "Investigate transformer failure and replace if necessary",
    solutionInfo: "Transformer replaced, backup generator installed",
    refusalReason: "",
    notes: "Critical infrastructure issue resolved",
    estimatedReviewTime: "6 hours",
    assignedMuktarId: "",
    assignedAdminId: "admin3",
    assignedManagerId: "mgr2",
  },
  {
    id: "6",
    trackingNumber: "TRK-006",
    district: "Al Faisaliyah",
    category: "roads",
    importance: Importance.MEDIUM,
    title: "Multiple cracks and sinkholes on secondary roads",
    description:
      "Multiple cracks and sinkholes on secondary roads in industrial area",
    status: ComplaintStatus.PENDING,
    createdAt: "2024-01-11T09:20:00Z",
    phoneNumber: "0935792468",
    attachments: [],
    pinned: false,
    submitterName: "Zahra Al-Saud",
    location: "Secondary roads in industrial area",
    citizenHelp: "Conduct road assessment and schedule repairs",
    solutionInfo: "",
    refusalReason: "",
    notes: "Assessment scheduled for next week",
    estimatedReviewTime: "5 days",
    assignedMuktarId: "muk5",
    assignedAdminId: "admin4",
    assignedManagerId: "",
  },
  {
    id: "7",
    trackingNumber: "TRK-007",
    district: "Al Wizarat",
    category: "sewage",
    importance: Importance.HIGH,
    title: "Sewage backup in multiple homes",
    description: "Sewage backup in multiple homes causing health hazard",
    status: ComplaintStatus.CLOSED,
    createdAt: "2024-01-10T11:15:00Z",
    phoneNumber: "0975318642",
    attachments: [],
    pinned: false,
    submitterName: "Mohammed Al-Official",
    location: "Residential Block D",
    citizenHelp: "Clear blockages and repair damaged pipes",
    solutionInfo: "",
    refusalReason:
      "Issue determined to be on private property, not municipal responsibility",
    notes: "Referred to private plumbing contractor",
    estimatedReviewTime: "2 days",
    assignedMuktarId: "muk6",
    assignedAdminId: "admin2",
    assignedManagerId: "mgr1",
  },
  {
    id: "8",
    trackingNumber: "TRK-008",
    district: "Al Safat",
    category: "noise",
    importance: Importance.LOW,
    title: "Excessive noise from construction site",
    description: "Excessive noise from construction site during quiet hours",
    status: ComplaintStatus.COMPLETED,
    createdAt: "2024-01-09T19:45:00Z",
    phoneNumber: "0946823571",
    attachments: [],
    pinned: false,
    submitterName: "Layla Al-Supervisor",
    location: "Construction site on Maple Avenue",
    citizenHelp: "Enforce noise ordinances and construction time limits",
    solutionInfo:
      "Construction company fined and ordered to comply with noise regulations",
    refusalReason: "",
    notes: "Resolved through regulatory enforcement",
    estimatedReviewTime: "3 days",
    assignedMuktarId: "muk7",
    assignedAdminId: "",
    assignedManagerId: "",
  },
  {
    id: "9",
    trackingNumber: "TRK-009",
    district: "Al Shifa",
    category: "parking",
    importance: Importance.LOW,
    title: "Illegal parking blocking emergency access",
    description: "Illegal parking blocking emergency access routes",
    status: ComplaintStatus.PENDING,
    createdAt: "2024-01-08T14:10:00Z",
    phoneNumber: "0968432175",
    attachments: [],
    pinned: false,
    submitterName: "Hassan Al-Mukhtar",
    location: "Emergency access behind shopping center",
    citizenHelp: "Install no-parking signs and increase enforcement",
    solutionInfo: "",
    refusalReason: "",
    notes: "Signs ordered, increased patrols scheduled",
    estimatedReviewTime: "1 week",
    assignedMuktarId: "",
    assignedAdminId: "",
    assignedManagerId: "",
  },
  {
    id: "10",
    trackingNumber: "TRK-010",
    district: "Al Manar",
    category: "green_spaces",
    importance: Importance.MEDIUM,
    title: "Park facilities damaged by vandalism",
    description: "Park facilities damaged by vandalism in playground area",
    status: ComplaintStatus.IN_PROGRESS,
    createdAt: "2024-01-07T08:30:00Z",
    phoneNumber: "0913579246",
    attachments: [],
    pinned: false,
    submitterName: "Sara Al-Manager",
    location: "Central Park playground area",
    citizenHelp: "Repair damaged equipment and improve security",
    solutionInfo: "",
    refusalReason: "",
    notes: "Repairs in progress, security cameras being installed",
    estimatedReviewTime: "4 days",
    assignedMuktarId: "",
    assignedAdminId: "admin5",
    assignedManagerId: "",
  },
  {
    id: "11",
    trackingNumber: "TRK-011",
    district: "Al Andalus",
    category: "traffic",
    importance: Importance.MEDIUM,
    title: "Traffic signal malfunction causing accidents",
    description:
      "Traffic signal malfunction causing accidents at busy intersection",
    status: ComplaintStatus.COMPLETED,
    createdAt: "2024-01-06T13:20:00Z",
    phoneNumber: "0986421357",
    attachments: [],
    pinned: false,
    submitterName: "Khalid Al-Admin",
    location: "Main Street & 1st Avenue intersection",
    citizenHelp: "Repair or replace faulty traffic signal",
    solutionInfo: "Signal controller replaced and synchronized",
    refusalReason: "",
    notes: "Traffic flow restored, accident rate monitored",
    estimatedReviewTime: "1 day",
    assignedMuktarId: "",
    assignedAdminId: "admin3",
    assignedManagerId: "",
  },
  {
    id: "12",
    trackingNumber: "TRK-012",
    district: "Al Hamra",
    category: "buildings",
    importance: Importance.HIGH,
    title: "Abandoned building posing safety hazard",
    description: "Abandoned building posing safety hazard to neighborhood",
    status: ComplaintStatus.PENDING,
    createdAt: "2024-01-05T10:45:00Z",
    phoneNumber: "0957283641",
    attachments: [],
    pinned: false,
    submitterName: "Nora Al-Citizen",
    location: "123 Commercial Street",
    citizenHelp: "Secure building and arrange for demolition or renovation",
    solutionInfo: "",
    refusalReason: "",
    notes: "Building inspector scheduled, legal proceedings initiated",
    estimatedReviewTime: "2 weeks",
    assignedMuktarId: "",
    assignedAdminId: "admin4",
    assignedManagerId: "mgr2",
  },
  {
    id: "13",
    trackingNumber: "TRK-013",
    district: "Al Olaya",
    category: "infrastructure",
    importance: Importance.MEDIUM,
    title: "Broken sidewalk causing accessibility issues",
    description:
      "Broken sidewalk with large cracks making it difficult for wheelchair users",
    status: ComplaintStatus.PENDING,
    createdAt: "2024-01-17T11:30:00Z",
    phoneNumber: "0911223344",
    attachments: [],
    pinned: false,
    submitterName: "Yusuf Al-Disabled",
    location: "Oak Street sidewalk",
    citizenHelp: "Repair the sidewalk to meet accessibility standards",
    solutionInfo: "",
    refusalReason: "",
    notes: "Accessibility concern - high priority for repair",
    estimatedReviewTime: "1 week",
    assignedMuktarId: "muk1",
    assignedAdminId: "admin1",
    assignedManagerId: "",
  },
  {
    id: "14",
    trackingNumber: "TRK-014",
    district: "Al Malaz",
    category: "sanitation",
    importance: Importance.LOW,
    title: "Overflowing public trash bin",
    description: "Public trash bin overflowing with waste attracting pests",
    status: ComplaintStatus.COMPLETED,
    createdAt: "2024-01-16T15:45:00Z",
    phoneNumber: "0998877665",
    attachments: [],
    pinned: false,
    submitterName: "Mariam Al-Resident",
    location: "Central Square",
    citizenHelp: "Empty the bin more frequently",
    solutionInfo: "Collection frequency increased",
    refusalReason: "",
    notes: "Resolved - additional collections scheduled",
    estimatedReviewTime: "1 day",
    assignedMuktarId: "muk2",
    assignedAdminId: "",
    assignedManagerId: "",
  },
  {
    id: "15",
    trackingNumber: "TRK-015",
    district: "Al Rawdah",
    category: "lighting",
    importance: Importance.MEDIUM,
    title: "Multiple street lights out in residential area",
    description: "Five street lights not working in the same block",
    status: ComplaintStatus.IN_PROGRESS,
    createdAt: "2024-01-18T20:15:00Z",
    phoneNumber: "0954433221",
    attachments: [],
    pinned: false,
    submitterName: "Ibrahim Al-Neighborhood",
    location: "Residential Block B",
    citizenHelp: "Replace all faulty lights in the area",
    solutionInfo: "",
    refusalReason: "",
    notes: "Electrician dispatched for assessment",
    estimatedReviewTime: "2 days",
    assignedMuktarId: "muk3",
    assignedAdminId: "admin2",
    assignedManagerId: "",
  },
];

// Mock Users Data
export const mockMuktars: User[] = [
  {
    id: "muk1",
    name: "Ahmed Hassan Al-Mukhtar",
    email: "ahmed.hassan@mukhtar.gov.sa",
    role: Role.MUKTAR,
    district: "Al Olaya",
    joinedAt: "2024-01-15",
  },
  {
    id: "muk2",
    name: "Fatima Al-Zahra Al-Mukhtar",
    email: "fatima.alzahra@mukhtar.gov.sa",
    role: Role.MUKTAR,
    district: "Al Malaz",
    joinedAt: "2024-02-20",
  },
  {
    id: "muk3",
    name: "Omar Ibn Khattab Al-Mukhtar",
    email: "omar.khattab@mukhtar.gov.sa",
    role: Role.MUKTAR,
    district: "Al Rawdah",
    joinedAt: "2024-03-10",
  },
  {
    id: "muk4",
    name: "Aisha Bint Abu Bakr Al-Mukhtar",
    email: "aisha.bakr@mukhtar.gov.sa",
    role: Role.MUKTAR,
    district: "Al Sulimaniyah",
    joinedAt: "2024-04-05",
  },
  {
    id: "muk5",
    name: "Ali Ibn Abi Talib Al-Mukhtar",
    email: "ali.talib@mukhtar.gov.sa",
    role: Role.MUKTAR,
    district: "Al Faisaliyah",
    joinedAt: "2024-05-12",
  },
  {
    id: "muk6",
    name: "Zahra Al-Saud Al-Mukhtar",
    email: "zahra.al-saud@mukhtar.gov.sa",
    role: Role.MUKTAR,
    district: "Al Wizarat",
    joinedAt: "2024-06-18",
  },
  {
    id: "muk7",
    name: "Hassan Al-Mukhtar",
    email: "hassan.al-mukhtar@mukhtar.gov.sa",
    role: Role.MUKTAR,
    district: "Al Safat",
    joinedAt: "2024-07-22",
  },
];

export const mockAdmins: User[] = [
  {
    id: "admin1",
    name: "Dr. Sarah Al-Admin",
    email: "sarah.aladmin@gov.sa",
    role: Role.ADMIN,
    district: "Central District",
    joinedAt: "2023-06-15",
  },
  {
    id: "admin2",
    name: "Mohammed Al-Official",
    email: "mohammed.alofficial@gov.sa",
    role: Role.ADMIN,
    district: "North District",
    joinedAt: "2023-08-22",
  },
  {
    id: "admin3",
    name: "Layla Al-Supervisor",
    email: "layla.alsupervisor@gov.sa",
    role: Role.ADMIN,
    district: "South District",
    joinedAt: "2023-09-30",
  },
  {
    id: "admin4",
    name: "Khalid Al-Manager",
    email: "khalid.almanager@gov.sa",
    role: Role.ADMIN,
    district: "East District",
    joinedAt: "2023-11-15",
  },
  {
    id: "admin5",
    name: "Nora Al-Coordinator",
    email: "nora.alcoordinator@gov.sa",
    role: Role.ADMIN,
    district: "West District",
    joinedAt: "2024-01-08",
  },
];

export const mockManagers: User[] = [
  {
    id: "mgr1",
    name: "Abdullah Al-Manager",
    email: "abdullah.almanager@gov.sa",
    role: Role.MANAGER,
    district: "City Center",
    joinedAt: "2023-01-15",
  },
  {
    id: "mgr2",
    name: "Maryam Al-Director",
    email: "maryam.aldirector@gov.sa",
    role: Role.MANAGER,
    district: "Metropolitan Area",
    joinedAt: "2023-03-20",
  },
];

// Mock Announcements Data
export const mockAnnouncements: Announcement[] = [
  {
    id: "ann1",
    title: "New Complaint Management System Launched",
    description:
      "We are excited to announce the launch of our enhanced complaint management system. This system will help us serve you better with faster response times and improved tracking.",
    date: "2024-01-15",
    category: "system",
    isSticky: true,
  },
  {
    id: "ann2",
    title: "Scheduled Maintenance - Sunday 2 AM - 4 AM",
    description:
      "The system will be under maintenance on Sunday from 2 AM to 4 AM. We apologize for any inconvenience this may cause. Services will resume normally after maintenance.",
    date: "2024-01-20",
    category: "maintenance",
    isSticky: false,
  },
  {
    id: "ann3",
    title: "New Citizen Feedback Portal",
    description:
      "We have launched a new feedback portal where citizens can provide suggestions for improving our services. Your input is valuable to us.",
    date: "2024-02-01",
    category: "service",
    isSticky: false,
  },
  {
    id: "ann4",
    title: "Emergency Contact Numbers Update",
    description:
      "Please note that our emergency contact numbers have been updated. For urgent complaints, please call the new 24/7 hotline: 920-000-123",
    date: "2024-02-15",
    category: "contact",
    isSticky: true,
  },
  {
    id: "ann5",
    title: "Community Meeting - March 10th",
    description:
      "Join us for a community meeting on March 10th at 7 PM in the Central Hall to discuss upcoming infrastructure projects in your area.",
    date: "2024-03-01",
    category: "community",
    isSticky: false,
  },
];

// Mock Achievements Data
export const mockAchievements: Achievement[] = [
  {
    id: "ach1",
    title: "Excellence in Service - 2024",
    description:
      "Awarded for outstanding service delivery and citizen satisfaction in complaint resolution",
    date: "2024-01-15",
    media: [{ url: "/achievement-excellence.png", type: "image" }],
  },
  {
    id: "ach2",
    title: "Community Service Award",
    description:
      "Recognized for exceptional community service and infrastructure improvements",
    date: "2024-02-20",
    media: [{ url: "/achievement-community.png", type: "image" }],
  },
  {
    id: "ach3",
    title: "Innovation in Public Administration",
    description:
      "Award for implementing innovative solutions in public complaint management",
    date: "2024-03-10",
    media: [{ url: "/achievement-innovation.png", type: "image" }],
  },
  {
    id: "ach4",
    title: "Environmental Excellence",
    description:
      "Recognition for outstanding environmental protection and green initiatives",
    date: "2024-04-05",
    media: [{ url: "/achievement-environment.png", type: "image" }],
  },
  {
    id: "ach5",
    title: "Digital Transformation Leader",
    description:
      "Award for leading digital transformation in municipal services",
    date: "2024-05-12",
    media: [{ url: "/achievement-digital.png", type: "image" }],
  },
];

// Helper function to filter complaints by role
export const getDemoComplaints = (role: Role): Complaint[] => {
  let filtered = [...mockComplaints];

  if (role === Role.MUKTAR) {
    // Mukhtar only sees LOW importance complaints
    filtered = mockComplaints.filter((c) => c.importance === Importance.LOW);
  } else if (role === Role.ADMIN) {
    // Admin sees MEDIUM + LOW importance complaints
    filtered = mockComplaints.filter(
      (c) =>
        c.importance === Importance.MEDIUM || c.importance === Importance.LOW
    );
  }
  // Manager sees all data (no filtering)

  return filtered;
};
